/*
 * Bundles the chrome's icon data into the app (#219).
 *
 * `@iconify/vue` resolves an icon it has not seen from api.iconify.design at
 * runtime, so every book boot made a handful of CDN requests and a book could
 * not render its own toolbar offline. This scans poveste's sources for the
 * icon names the chrome uses, extracts exactly those from the collection
 * packages, and writes them to `src/app/util/icons.generated.ts`, which the
 * app registers at boot. Story icons a user sets stay on the runtime lookup.
 *
 * The generated file is committed; `icons.spec.ts` fails when it is stale.
 *
 *   pnpm --filter @poveste/app icons
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { dirname, resolve } from 'node:path'
import process from 'node:process'
import { fileURLToPath, pathToFileURL } from 'node:url'
import { getIcons } from '@iconify/utils'
import { globbySync } from 'globby'

const require = createRequire(import.meta.url)
const here = dirname(fileURLToPath(import.meta.url))
const packageRoot = resolve(here, '..')
const packagesRoot = resolve(packageRoot, '..')

export const OUTPUT = resolve(packageRoot, 'src/app/util/icons.generated.ts')

// Collections the chrome draws from. Adding a prefix here means adding its
// `@iconify-json/*` package to devDependencies.
const PREFIXES = ['carbon', 'fluent', 'mdi', 'ri']
const ICON_RE = new RegExp(`['"\`]((?:${PREFIXES.join('|')}):[a-z0-9-]+)['"\`]`, 'g')

/** Every `prefix:name` literal in poveste's own sources, grouped by prefix. */
export function scanIconNames() {
  const files = globbySync(['*/src/**/*.{vue,ts,js,mjs}'], {
    cwd: packagesRoot,
    absolute: true,
    ignore: ['**/node_modules/**', '**/dist/**', '**/__tests__/**', '**/*.generated.ts'],
  })
  const byPrefix = new Map(PREFIXES.map(p => [p, new Set()]))
  for (const file of files) {
    const source = readFileSync(file, 'utf8')
    for (const match of source.matchAll(ICON_RE)) {
      const [prefix, name] = match[1].split(':')
      byPrefix.get(prefix).add(name)
    }
  }
  return byPrefix
}

/** The TypeScript source of the generated module. Deterministic: sorted, stable JSON. */
export function generate() {
  const collections = []
  for (const [prefix, names] of scanIconNames()) {
    if (!names.size) continue
    const full = require(`@iconify-json/${prefix}/icons.json`)
    const subset = getIcons(full, [...names].sort())
    if (!subset) continue
    const missing = [...names].filter(n => !subset.icons[n] && !subset.aliases?.[n])
    if (missing.length) {
      throw new Error(`${prefix}: icons not in @iconify-json/${prefix}: ${missing.join(', ')}`)
    }
    collections.push(subset)
  }
  const body = collections.map(c => `  ${JSON.stringify(c)},`).join('\n')
  return `// Generated by scripts/icons.mjs — do not edit. Refresh with \`pnpm --filter @poveste/app icons\`.
import type { IconifyJSON } from '@iconify/vue'

export const iconCollections: IconifyJSON[] = [
${body}
]
`
}

// `--check`: exit 1 when the committed file is stale, for the unit test.
function main() {
  const source = generate()
  if (process.argv.includes('--check')) {
    const current = readFileSync(OUTPUT, 'utf8')
    if (current !== source) {
      console.error('icons.generated.ts is stale — run `pnpm --filter @poveste/app icons`')
      process.exit(1)
    }
    return
  }
  writeFileSync(OUTPUT, source)
  const count = [...source.matchAll(/"body":/g)].length
  console.error(`icons.generated.ts: ${count} icons`)
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  main()
}
