export const STATE_SYNC = '__poveste:state-sync'
export const SANDBOX_READY = '__poveste:sandbox-ready'
export const EVENT_SEND = '__poveste:event'
export const PREVIEW_SETTINGS_SYNC = '__poveste:preview-settings-sync'
export const PREVIEW_SETTINGS_REQUEST = '__poveste:preview-settings-request'
export const SANDBOX_HEIGHT = '__poveste:sandbox-height'
